//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jcl.Tools.WindowsForms.ToolbarImagePicker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings_Spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings_Spanish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jcl.Tools.WindowsForms.ToolbarImagePicker.LocalizedStrings_Spanish", typeof(LocalizedStrings_Spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer también la imagen {1} en {2} &quot;{0}.
        /// </summary>
        internal static string AllowSmallLarge {
            get {
                return ResourceManager.GetString("AllowSmallLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grande.
        /// </summary>
        internal static string AllowSmallLargeLarge {
            get {
                return ResourceManager.GetString("AllowSmallLargeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to las propiedades.
        /// </summary>
        internal static string AllowSmallLargePropertyPlural {
            get {
                return ResourceManager.GetString("AllowSmallLargePropertyPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la propiedad.
        /// </summary>
        internal static string AllowSmallLargePropertySingular {
            get {
                return ResourceManager.GetString("AllowSmallLargePropertySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pequeña.
        /// </summary>
        internal static string AllowSmallLargeSmall {
            get {
                return ResourceManager.GetString("AllowSmallLargeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar imagen de recurso.
        /// </summary>
        internal static string EditorTitle {
            get {
                return ResourceManager.GetString("EditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar....
        /// </summary>
        internal static string SearchCue {
            get {
                return ResourceManager.GetString("SearchCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha seleccionado una imagen grande para una propiedad de imagen pequeña. ¿Está seguro?.
        /// </summary>
        internal static string SelectingDifferentLarge {
            get {
                return ResourceManager.GetString("SelectingDifferentLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha seleccionado una imagen pequeña para una propiedad de imagen grande. ¿Está seguro?.
        /// </summary>
        internal static string SelectingDifferentSmall {
            get {
                return ResourceManager.GetString("SelectingDifferentSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string SelectingDifferentTitle {
            get {
                return ResourceManager.GetString("SelectingDifferentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguna imagen seleccionada.
        /// </summary>
        internal static string SelectingNoImage {
            get {
                return ResourceManager.GetString("SelectingNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SelectingNoImageTitle {
            get {
                return ResourceManager.GetString("SelectingNoImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector de recursos de Visual Studio.
        /// </summary>
        internal static string ToolbarPickerResourcePicker {
            get {
                return ResourceManager.GetString("ToolbarPickerResourcePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector de Imagenes.
        /// </summary>
        internal static string ToolbarPickerTabTitle {
            get {
                return ResourceManager.GetString("ToolbarPickerTabTitle", resourceCulture);
            }
        }
    }
}
